#!/usr/bin/env python

import unittest

# import sys
# sys.path.insert(0,'./cx_asap/')
from system_files.utils import Config, Generate
import os
import re


class testGenerate(unittest.TestCase):
    def setUp(self):
        """setup to test test system_files.utils.Generate to confirm
        parameter.yaml required subset is read and stored in self.param."""
        self.required_top_level = {
            "module-platon-squeeze": ["file_name"],
            "pipeline-platon-squeeze": ["experiment_location"],
            "module-adp-analysis": ["csv_path", "cell_path"],
            "module-refinement": [
                "structure_location",
                "reference_path",
                "refinements_to_check",
                "tolerance",
                "maximum_cycles",
            ],
            "pipeline-refinement": [
                "experiment_location",
                "reference_path",
                "refinements_to_check",
                "tolerance",
                "maximum_cycles",
            ],
            "pipeline-variable-position": [
                "location_of_frames",
                "experiment_name",
                "reference_structure_location",
                "reference_XDS_INP_location",
                "reference_background_files_location",
                "instrument_parameters_path",
                "instrument_cif_path",
                "maximum_processors",
                "neggia_library",
                "space_group_number",
                "atoms_for_rotation_analysis",
                "reference_plane",
                "chemical_formula",
                "crystal_colour",
                "crystal_habit",
                "max_crystal_dimension",
                "middle_crystal_dimension",
                "min_crystal_dimension",
                "refinements_to_check",
                "tolerance",
                "maximum_cycles",
                "cif_parameters",
                "structural_analysis_bonds",
                "structural_analysis_angles",
                "structural_analysis_torsions",
                "ADP_analysis",
                "atoms_for_analysis",
                "wedge_angles",
                "min_pixels",
                "spot_maximum_centroid",
                "strong_pixels",
                "sepmin",
                "mapping_step_size",
                "total_angle",
            ],
            "pipeline-general": [
                "experiment_location",
                "reference_cif_location",
                "refinements_to_check",
                "tolerance",
                "maximum_cycles",
                "cif_parameters",
                "structural_analysis_bonds",
                "structural_analysis_angles",
                "structural_analysis_torsions",
                "ADP_analysis",
                "atoms_for_analysis",
                "varying_cif_parameter",
                "varying_parameter_values",
            ],
            "pipeline-general-extra": [
                "reference_location",
                "experiment_location",
                "_chemical_formula_moiety",
                "_chemical_absolute_configuration",
                "_exptl_absorpt_correction_T_max",
                "_exptl_absorpt_correction_T_min",
                "_exptl_absorpt_correction_type",
                "_exptl_crystal_colour",
                "_exptl_crystal_description",
                "_exptl_crystal_size_max",
                "_exptl_crystal_size_mid",
                "_exptl_crystal_size_min",
                "_diffrn_detector",
                "_diffrn_detector_area_resol_mean",
                "_diffrn_detector_type",
                "_diffrn_measurement_device",
                "_diffrn_measurement_device_type",
                "_diffrn_measurement_method",
                "_diffrn_radiation_monochromator",
                "_diffrn_radiation_probe",
                "_diffrn_radiation_type",
                "_diffrn_radiation_wavelength",
                "_diffrn_source",
                "_diffrn_source_type",
                "_computing_cell_refinement",
                "_computing_data_collection",
                "_computing_data_reduction",
                "_computing_molecular_graphics",
                "_computing_publication_material",
                "_computing_structure_refinement",
                "_computing_structure_solution",
                "refinements_to_check",
                "tolerance",
                "maximum_cycles",
                "cif_parameters",
                "structural_analysis_bonds",
                "structural_analysis_angles",
                "structural_analysis_torsions",
                "ADP_analysis",
                "atoms_for_analysis",
                "varying_cif_parameter",
                "varying_parameter_values",
            ],
            "module-intensity-compare": [
                "xprep_file_name",
                "h_condition_1",
                "h_condition_2",
                "k_condition_1",
                "k_condition_2",
                "l_condition_1",
                "l_condition_2",
                "a_axis",
                "b_axis",
                "c_axis",
                "alpha",
                "beta",
                "gamma",
                "h+k_condition_1",
                "h+k_condition_2",
                "h+l_condition_1",
                "h+l_condition_2",
                "k+l_condition_1",
                "k+l_condition_2",
                "h+k+l_condition_1",
                "h+k+l_condition_2",
                "include_h_0_condition_1",
                "include_h_0_condition_2",
                "include_k_0_condition_1",
                "include_k_0_condition_2",
                "include_l_0_condition_1",
                "include_l_0_condition_2",
            ],
            "pipeline-intensity-compare": [
                "data_location",
                "h_condition_1",
                "h_condition_2",
                "k_condition_1",
                "k_condition_2",
                "l_condition_1",
                "l_condition_2",
                "h+k_condition_1",
                "h+k_condition_2",
                "h+l_condition_1",
                "h+l_condition_2",
                "k+l_condition_1",
                "k+l_condition_2",
                "h+k+l_condition_1",
                "h+k+l_condition_2",
                "a_axis",
                "b_axis",
                "c_axis",
                "alpha",
                "beta",
                "gamma",
                "include_h_0_condition_1",
                "include_h_0_condition_2",
                "include_k_0_condition_1",
                "include_k_0_condition_2",
                "include_l_0_condition_1",
                "include_l_0_condition_2",
            ],
            "module-cif-merge": ["instrument_cif", "new_cif"],
            "module-make-instrument-cif": ["reference_cif"],
            "pipeline-cif-combine": ["location_of_cifs"],
            "pipeline-cif": [
                "experiment_location",
                "instrument_ending",
                "instrument_file",
                "structure_solution",
                "chemical_formula",
                "crystal_habit",
                "crystal_colour",
                "max_crystal_dimension",
                "middle_crystal_dimension",
                "min_crystal_dimension",
            ],
            "pipeline-rigaku-vt": [
                "experiment_location",
                "reference_location",
                "chemical_formula",
                "crystal_colour",
                "crystal_habit",
                "max_crystal_dimension",
                "middle_crystal_dimension",
                "min_crystal_dimension",
                "refinements_to_check",
                "tolerance",
                "maximum_cycles",
                "cif_parameters",
                "structural_analysis_bonds",
                "structural_analysis_angles",
                "structural_analysis_torsions",
                "ADP_analysis",
                "atoms_for_analysis",
            ],
            "pipeline-aus-synch-vt": [
                "location_of_autoprocess_folders",
                "experiment_name",
                "reference_location",
                "atoms_for_rotation_analysis",
                "reference_plane",
                "chemical_formula",
                "crystal_colour",
                "crystal_habit",
                "max_crystal_dimension",
                "middle_crystal_dimension",
                "min_crystal_dimension",
                "refinements_to_check",
                "tolerance",
                "maximum_cycles",
                "cif_parameters",
                "structural_analysis_bonds",
                "structural_analysis_angles",
                "structural_analysis_torsions",
                "ADP_analysis",
                "atoms_for_analysis",
                "transformation_matrix"
            ],
            "module-xds-cell-transform": ["XDS_ASCII_File_1", "XDS_ASCII_File_2"],
            "module-xds-reprocess": [
                "xds_template_name",
                "XDS_INP_path",
                "experiment_location",
            ],
            "module-xprep": [
                "xprep_file_name",
                "transformation_matrix",
                "space_group",
                "chemical_formula",
                "experiment_location",
            ],
            "pipeline-xds-reprocess": ["XDS_INP_path", "experiment_location"],
            "pipeline-xprep": [
                "xprep_file_name",
                "transformation_matrix",
                "space_group",
                "chemical_formula",
                "experiment_location",
            ],
            "module-cell-analysis": [
                "csv_location",
                "reference_unit_cell",
                "x_axis_header",
            ],
            "module-cif-read": [
                "cif_parameters",
                "structural_analysis_bonds",
                "structural_analysis_angles",
                "structural_analysis_torsions",
                "ADP_analysis",
                "folder_containing_cifs",
            ],
            "module-rotation-planes": ["reference_plane", "lst_file_location"],
            "module-structural-analysis": [
                "atoms_for_analysis",
                "bond_data",
                "angle_data",
                "torsion_data",
            ],
            "pipeline-rotation-planes": ["reference_plane", "experiment_location"],
            "pipeline-variable-analysis": [
                "cif_parameters",
                "atoms_for_analysis",
                "structural_analysis_bonds",
                "structural_analysis_angles",
                "structural_analysis_torsions",
                "ADP_analysis",
                "varying_cif_parameter",
                "experiment_location",
                "reference_unit_cell",
            ],
            "pipeline-position-analysis": [
                "cif_parameters",
                "atoms_for_analysis",
                "reference_plane",
                "structural_analysis_bonds",
                "structural_analysis_angles",
                "structural_analysis_torsions",
                "ADP_analysis",
                "experiment_location",
                "reference_unit_cell",
                "atoms_for_plane",
                "wedge_angles",
                "min_pixels",
                "spot_maximum_centroid",
                "strong_pixels",
                "sepmin",
                "mapping_step_size",
            ],
            "pipeline-temperature-analysis": [
                "cif_parameters",
                "atoms_for_analysis",
                "structural_analysis_bonds",
                "structural_analysis_angles",
                "structural_analysis_torsions",
                "ADP_analysis",
                "experiment_location",
                "reference_unit_cell",
            ],
            "pipeline-AS-Brute": ["experiment_location"],
            "module-molecule-reconstruction": [
                "reference_path",
                "atom_list",
                "bond_list",
                "starting_atom",
                "starting_coordinates",
                "a_gradient",
                "b_gradient",
                "c_gradient",
                "alpha_gradient",
                "beta_gradient",
                "gamma_gradient",
                "max_position",
                "min_position",
                "position_step_size",
            ],
        }

        self.required_second_level = [
            ["file_name"],
            ["experiment_location"],
            ["csv_path", "cell_path"],
            [
                "structure_location",
                "reference_path",
                "refinements_to_check",
                "tolerance",
                "maximum_cycles",
            ],
            [
                "experiment_location",
                "reference_path",
                "refinements_to_check",
                "tolerance",
                "maximum_cycles",
            ],
            [
                "location_of_frames",
                "experiment_name",
                "reference_structure_location",
                "reference_XDS_INP_location",
                "reference_background_files_location",
                "instrument_parameters_path",
                "instrument_cif_path",
                "maximum_processors",
                "neggia_library",
                "space_group_number",
                "atoms_for_rotation_analysis",
                "reference_plane",
                "chemical_formula",
                "crystal_colour",
                "crystal_habit",
                "max_crystal_dimension",
                "middle_crystal_dimension",
                "min_crystal_dimension",
                "refinements_to_check",
                "tolerance",
                "maximum_cycles",
                "cif_parameters",
                "structural_analysis_bonds",
                "structural_analysis_angles",
                "structural_analysis_torsions",
                "ADP_analysis",
                "atoms_for_analysis",
                "wedge_angles",
                "min_pixels",
                "spot_maximum_centroid",
                "strong_pixels",
                "sepmin",
                "mapping_step_size",
                "total_angle",
            ],
            [
                "experiment_location",
                "reference_cif_location",
                "refinements_to_check",
                "tolerance",
                "maximum_cycles",
                "cif_parameters",
                "structural_analysis_bonds",
                "structural_analysis_angles",
                "structural_analysis_torsions",
                "ADP_analysis",
                "atoms_for_analysis",
                "varying_cif_parameter",
                "varying_parameter_values",
            ],
            [
                "reference_location",
                "experiment_location",
                "_chemical_formula_moiety",
                "_chemical_absolute_configuration",
                "_exptl_absorpt_correction_T_max",
                "_exptl_absorpt_correction_T_min",
                "_exptl_absorpt_correction_type",
                "_exptl_crystal_colour",
                "_exptl_crystal_description",
                "_exptl_crystal_size_max",
                "_exptl_crystal_size_mid",
                "_exptl_crystal_size_min",
                "_diffrn_detector",
                "_diffrn_detector_area_resol_mean",
                "_diffrn_detector_type",
                "_diffrn_measurement_device",
                "_diffrn_measurement_device_type",
                "_diffrn_measurement_method",
                "_diffrn_radiation_monochromator",
                "_diffrn_radiation_probe",
                "_diffrn_radiation_type",
                "_diffrn_radiation_wavelength",
                "_diffrn_source",
                "_diffrn_source_type",
                "_computing_cell_refinement",
                "_computing_data_collection",
                "_computing_data_reduction",
                "_computing_molecular_graphics",
                "_computing_publication_material",
                "_computing_structure_refinement",
                "_computing_structure_solution",
                "refinements_to_check",
                "tolerance",
                "maximum_cycles",
                "cif_parameters",
                "structural_analysis_bonds",
                "structural_analysis_angles",
                "structural_analysis_torsions",
                "ADP_analysis",
                "atoms_for_analysis",
                "varying_cif_parameter",
                "varying_parameter_values",
            ],
            [
                "xprep_file_name",
                "h_condition_1",
                "h_condition_2",
                "k_condition_1",
                "k_condition_2",
                "l_condition_1",
                "l_condition_2",
                "a_axis",
                "b_axis",
                "c_axis",
                "alpha",
                "beta",
                "gamma",
                "h+k_condition_1",
                "h+k_condition_2",
                "h+l_condition_1",
                "h+l_condition_2",
                "k+l_condition_1",
                "k+l_condition_2",
                "h+k+l_condition_1",
                "h+k+l_condition_2",
                "include_h_0_condition_1",
                "include_h_0_condition_2",
                "include_k_0_condition_1",
                "include_k_0_condition_2",
                "include_l_0_condition_1",
                "include_l_0_condition_2",
            ],
            [
                "data_location",
                "h_condition_1",
                "h_condition_2",
                "k_condition_1",
                "k_condition_2",
                "l_condition_1",
                "l_condition_2",
                "h+k_condition_1",
                "h+k_condition_2",
                "h+l_condition_1",
                "h+l_condition_2",
                "k+l_condition_1",
                "k+l_condition_2",
                "h+k+l_condition_1",
                "h+k+l_condition_2",
                "a_axis",
                "b_axis",
                "c_axis",
                "alpha",
                "beta",
                "gamma",
                "include_h_0_condition_1",
                "include_h_0_condition_2",
                "include_k_0_condition_1",
                "include_k_0_condition_2",
                "include_l_0_condition_1",
                "include_l_0_condition_2",
            ],
            ["instrument_cif", "new_cif"],
            ["reference_cif"],
            ["location_of_cifs"],
            [
                "experiment_location",
                "instrument_ending",
                "instrument_file",
                "structure_solution",
                "chemical_formula",
                "crystal_habit",
                "crystal_colour",
                "max_crystal_dimension",
                "middle_crystal_dimension",
                "min_crystal_dimension",
            ],
            [
                "experiment_location",
                "reference_location",
                "chemical_formula",
                "crystal_colour",
                "crystal_habit",
                "max_crystal_dimension",
                "middle_crystal_dimension",
                "min_crystal_dimension",
                "refinements_to_check",
                "tolerance",
                "maximum_cycles",
                "cif_parameters",
                "structural_analysis_bonds",
                "structural_analysis_angles",
                "structural_analysis_torsions",
                "ADP_analysis",
                "atoms_for_analysis",
            ],
            [
                "location_of_autoprocess_folders",
                "experiment_name",
                "reference_location",
                "atoms_for_rotation_analysis",
                "reference_plane",
                "chemical_formula",
                "crystal_colour",
                "crystal_habit",
                "max_crystal_dimension",
                "middle_crystal_dimension",
                "min_crystal_dimension",
                "refinements_to_check",
                "tolerance",
                "maximum_cycles",
                "cif_parameters",
                "structural_analysis_bonds",
                "structural_analysis_angles",
                "structural_analysis_torsions",
                "ADP_analysis",
                "atoms_for_analysis",
                "transformation_matrix",
            ],
            ["XDS_ASCII_File_1", "XDS_ASCII_File_2"],
            ["xds_template_name", "XDS_INP_path", "experiment_location"],
            [
                "xprep_file_name",
                "transformation_matrix",
                "space_group",
                "chemical_formula",
                "experiment_location",
            ],
            ["XDS_INP_path", "experiment_location"],
            [
                "xprep_file_name",
                "transformation_matrix",
                "space_group",
                "chemical_formula",
                "experiment_location",
            ],
            ["csv_location", "reference_unit_cell", "x_axis_header"],
            [
                "cif_parameters",
                "structural_analysis_bonds",
                "structural_analysis_angles",
                "structural_analysis_torsions",
                "ADP_analysis",
                "folder_containing_cifs",
            ],
            ["reference_plane", "lst_file_location"],
            ["atoms_for_analysis", "bond_data", "angle_data", "torsion_data"],
            ["reference_plane", "experiment_location"],
            [
                "cif_parameters",
                "atoms_for_analysis",
                "structural_analysis_bonds",
                "structural_analysis_angles",
                "structural_analysis_torsions",
                "ADP_analysis",
                "varying_cif_parameter",
                "experiment_location",
                "reference_unit_cell",
            ],
            [
                "cif_parameters",
                "atoms_for_analysis",
                "reference_plane",
                "structural_analysis_bonds",
                "structural_analysis_angles",
                "structural_analysis_torsions",
                "ADP_analysis",
                "experiment_location",
                "reference_unit_cell",
                "atoms_for_plane",
                "wedge_angles",
                "min_pixels",
                "spot_maximum_centroid",
                "strong_pixels",
                "sepmin",
                "mapping_step_size",
            ],
            [
                "cif_parameters",
                "atoms_for_analysis",
                "structural_analysis_bonds",
                "structural_analysis_angles",
                "structural_analysis_torsions",
                "ADP_analysis",
                "experiment_location",
                "reference_unit_cell",
            ],
            ["experiment_location"],
            [
                "reference_path",
                "atom_list",
                "bond_list",
                "starting_atom",
                "starting_coordinates",
                "a_gradient",
                "b_gradient",
                "c_gradient",
                "alpha_gradient",
                "beta_gradient",
                "gamma_gradient",
                "max_position",
                "min_position",
                "position_step_size",
            ],
        ]
        self.parameters = Generate().param

    def test_top_level_required(self):
        """Prevent deletions/typos in top level required modules"""
        required = set(self.required_top_level)
        present = set(self.parameters).intersection(required)
        self.assertEqual(required, present)

    def test_top_level_keys(self):
        """Prevent deletions/typos in key list of top level required modules"""
        present = []
        for key in self.required_top_level:
            present.append(self.parameters[key])
        self.assertEqual(self.required_second_level, present)


class testConfig(unittest.TestCase):
    def setUp(self):
        """setup the class for running below tests"""
        self.test = Config(test_mode=True)

        self.correct_filled_params = {
            "module-refinement": {
                "structure_location": "test_data/data/200K/200.ins",
                "reference_path": "test_data/ref/ref.res",
                "refinements_to_check": 4,
                "tolerance": 0.005,
                "maximum_cycles": 10,
            },
            "pipeline-refinement": {
                "experiment_location": "test_data/data",
                "reference_path": "test_data/ref/ref.res",
                "refinements_to_check": 4,
                "tolerance": 0.005,
                "maximum_cycles": 10,
            },
            "module-cif-merge": {
                "instrument_cif": "test_data/ref/instrument.cif",
                "new_cif": "test_data/data/200K/200.cif",
            },
            "module-make-instrument-cif": {"reference_cif": "test_data/ref/ref.cif"},
            "module-cif-read": {
                "cif_parameters": [
                    "_cell_length_a",
                    "_cell_length_b",
                    "_cell_length_c",
                    "_cell_angle_alpha",
                    "_cell_angle_beta",
                    "_cell_angle_gamma",
                    "_cell_volume",
                    "_diffrn_reflns_av_R_equivalents",
                    "_diffrn_measured_fraction_theta_full",
                    "_diffrn_ambient_temperature",
                    "_refine_ls_R_factor_gt",
                ],
                "structural_analysis_angles": True,
                "structural_analysis_bonds": True,
                "structural_analysis_torsions": True,
                "folder_containing_cifs": "test_data/data",
                "ADP_analysis": True,
            },
            "pipeline-cif": {
                "experiment_location": "test_data/data",
                "instrument_ending": False,
                "instrument_file": "instrument.cif",
                "structure_solution": "shelxt",
                "chemical_formula": "Cu C10 H14 O4",
                "crystal_habit": "needle",
                "crystal_colour": "blue",
                "max_crystal_dimension": 0.2,
                "middle_crystal_dimension": 0.08,
                "min_crystal_dimension": 0.05,
            },
            "module-cell-analysis": {
                "csv_location": "test_data/data/CIF_Parameters.csv",
                "reference_unit_cell": "test_data/ref/ref.res",
                "x_axis_header": "_diffrn_ambient_temperature",
            },
            "module-structural-analysis": {
                "atoms_for_analysis": ["Cu1"],
                "bond_data": "test_data/data/Bond_Lengths.csv",
                "angle_data": "test_data/data/Bond_Angles.csv",
                "torsion_data": "test_data/data/Bond_Torsions.csv",
            },
            "pipeline-variable-analysis": {
                "cif_parameters": [
                    "_cell_length_a",
                    "_cell_length_b",
                    "_cell_length_c",
                    "_cell_angle_alpha",
                    "_cell_angle_beta",
                    "_cell_angle_gamma",
                    "_cell_volume",
                    "_diffrn_reflns_av_R_equivalents",
                    "_diffrn_measured_fraction_theta_full",
                    "_diffrn_ambient_temperature",
                    "_refine_ls_R_factor_gt",
                ],
                "atoms_for_analysis": ["Cu1"],
                "structural_analysis_angles": True,
                "structural_analysis_bonds": True,
                "structural_analysis_torsions": True,
                "ADP_analysis": True,
                "varying_cif_parameter": "_diffrn_ambient_temperature",
                "experiment_location": "test_data/data",
                "reference_unit_cell": "test_data/ref/ref.res",
            },
            "pipeline-general": {
                "experiment_location": "test_data/data",
                "reference_cif_location": "test_data/ref/ref.cif",
                "refinements_to_check": 4,
                "tolerance": 0.005,
                "maximum_cycles": 10,
                "cif_parameters": [
                    "_cell_length_a",
                    "_cell_length_b",
                    "_cell_length_c",
                    "_cell_angle_alpha",
                    "_cell_angle_beta",
                    "_cell_angle_gamma",
                    "_cell_volume",
                    "_diffrn_reflns_av_R_equivalents",
                    "_diffrn_measured_fraction_theta_full",
                    "_diffrn_ambient_temperature",
                    "_refine_ls_R_factor_gt",
                ],
                "structural_analysis_bonds": True,
                "structural_analysis_angles": True,
                "structural_analysis_torsions": True,
                "ADP_analysis": True,
                "atoms_for_analysis": ["Cu1"],
                "varying_cif_parameter": "_diffrn_ambient_temperature",
                "varying_parameter_values": [
                    "200(2)",
                    "210(2)",
                    "220(2)",
                    "230(2)",
                    "240(2)",
                ],
            },
            "hello there": "General Kenobi",
        }

        self.correct_all_params = {
            "module-refinement": {
                "structure_location": "test_data/data/200K/200.ins",
                "reference_path": "test_data/ref/ref.res",
                "refinements_to_check": 4,
                "tolerance": 0.005,
                "maximum_cycles": 10,
            },
            "pipeline-refinement": {
                "experiment_location": "test_data/data",
                "reference_path": "test_data/ref/ref.res",
                "refinements_to_check": 4,
                "tolerance": 0.005,
                "maximum_cycles": 10,
            },
            "module-cif-merge": {
                "instrument_cif": "test_data/ref/instrument.cif",
                "new_cif": "test_data/data/200K/200.cif",
            },
            "module-make-instrument-cif": {"reference_cif": "test_data/ref/ref.cif"},
            "module-cif-read": {
                "cif_parameters": [
                    "_cell_length_a",
                    "_cell_length_b",
                    "_cell_length_c",
                    "_cell_angle_alpha",
                    "_cell_angle_beta",
                    "_cell_angle_gamma",
                    "_cell_volume",
                    "_diffrn_reflns_av_R_equivalents",
                    "_diffrn_measured_fraction_theta_full",
                    "_diffrn_ambient_temperature",
                    "_refine_ls_R_factor_gt",
                ],
                "structural_analysis_angles": True,
                "structural_analysis_bonds": True,
                "structural_analysis_torsions": True,
                "folder_containing_cifs": "test_data/data",
                "ADP_analysis": True,
            },
            "pipeline-cif": {
                "experiment_location": "test_data/data",
                "instrument_ending": False,
                "instrument_file": "instrument.cif",
                "structure_solution": "shelxt",
                "chemical_formula": "Cu C10 H14 O4",
                "crystal_habit": "needle",
                "crystal_colour": "blue",
                "max_crystal_dimension": 0.2,
                "middle_crystal_dimension": 0.08,
                "min_crystal_dimension": 0.05,
            },
            "module-cell-analysis": {
                "csv_location": "test_data/data/CIF_Parameters.csv",
                "reference_unit_cell": "test_data/ref/ref.res",
                "x_axis_header": "_diffrn_ambient_temperature",
            },
            "module-structural-analysis": {
                "atoms_for_analysis": ["Cu1"],
                "bond_data": "test_data/data/Bond_Lengths.csv",
                "angle_data": "test_data/data/Bond_Angles.csv",
                "torsion_data": "test_data/data/Bond_Torsions.csv",
            },
            "pipeline-variable-analysis": {
                "cif_parameters": [
                    "_cell_length_a",
                    "_cell_length_b",
                    "_cell_length_c",
                    "_cell_angle_alpha",
                    "_cell_angle_beta",
                    "_cell_angle_gamma",
                    "_cell_volume",
                    "_diffrn_reflns_av_R_equivalents",
                    "_diffrn_measured_fraction_theta_full",
                    "_diffrn_ambient_temperature",
                    "_refine_ls_R_factor_gt",
                ],
                "atoms_for_analysis": ["Cu1"],
                "structural_analysis_angles": True,
                "structural_analysis_bonds": True,
                "structural_analysis_torsions": True,
                "ADP_analysis": True,
                "varying_cif_parameter": "_diffrn_ambient_temperature",
                "experiment_location": "test_data/data",
                "reference_unit_cell": "test_data/ref/ref.res",
            },
            "pipeline-general": {
                "experiment_location": "test_data/data",
                "reference_cif_location": "test_data/ref/ref.cif",
                "refinements_to_check": 4,
                "tolerance": 0.005,
                "maximum_cycles": 10,
                "cif_parameters": [
                    "_cell_length_a",
                    "_cell_length_b",
                    "_cell_length_c",
                    "_cell_angle_alpha",
                    "_cell_angle_beta",
                    "_cell_angle_gamma",
                    "_cell_volume",
                    "_diffrn_reflns_av_R_equivalents",
                    "_diffrn_measured_fraction_theta_full",
                    "_diffrn_ambient_temperature",
                    "_refine_ls_R_factor_gt",
                ],
                "structural_analysis_bonds": True,
                "structural_analysis_angles": True,
                "structural_analysis_torsions": True,
                "ADP_analysis": True,
                "atoms_for_analysis": ["Cu1"],
                "varying_cif_parameter": "_diffrn_ambient_temperature",
                "varying_parameter_values": [
                    "200(2)",
                    "210(2)",
                    "220(2)",
                    "230(2)",
                    "240(2)",
                ],
            },
            "home_path": None,
            "analysis_path": None,
            "ref_path": None,
            "results_path": None,
            "failed_path": None,
            "ref_path_organised": None,
            "current_results_path": None,
            "process_counter": None,
            "hello there": "General Kenobi",
            "Structures_in_each_CIF": [None],
            "Successful_Positions": [None],
            "ref_a": None,
            "ref_b": None,
            "ref_c": None,
            "ref_alpha": None,
            "ref_beta": None,
            "ref_gamma": None,
            "ref_volume": None,
            "space_group": None,
            "frames_path": None,
            "XDS_inp_organised": None,
            "start_angle": None,
            "total_angle": None,
            "total_frames": None,
        }

        self.correct_fields = [
            {
                "structure_location": "test_data/data/200K/200.ins",
                "reference_path": "test_data/ref/ref.res",
                "refinements_to_check": 4,
                "tolerance": 0.005,
                "maximum_cycles": 10,
            },
            {
                "experiment_location": "test_data/data",
                "reference_path": "test_data/ref/ref.res",
                "refinements_to_check": 4,
                "tolerance": 0.005,
                "maximum_cycles": 10,
            },
            {
                "instrument_cif": "test_data/ref/instrument.cif",
                "new_cif": "test_data/data/200K/200.cif",
            },
            {"reference_cif": "test_data/ref/ref.cif"},
            {
                "cif_parameters": [
                    "_cell_length_a",
                    "_cell_length_b",
                    "_cell_length_c",
                    "_cell_angle_alpha",
                    "_cell_angle_beta",
                    "_cell_angle_gamma",
                    "_cell_volume",
                    "_diffrn_reflns_av_R_equivalents",
                    "_diffrn_measured_fraction_theta_full",
                    "_diffrn_ambient_temperature",
                    "_refine_ls_R_factor_gt",
                ],
                "structural_analysis_angles": True,
                "structural_analysis_bonds": True,
                "structural_analysis_torsions": True,
                "folder_containing_cifs": "test_data/data",
                "ADP_analysis": True,
            },
            {
                "experiment_location": "test_data/data",
                "instrument_ending": False,
                "instrument_file": "instrument.cif",
                "structure_solution": "shelxt",
                "chemical_formula": "Cu C10 H14 O4",
                "crystal_habit": "needle",
                "crystal_colour": "blue",
                "max_crystal_dimension": 0.2,
                "middle_crystal_dimension": 0.08,
                "min_crystal_dimension": 0.05,
            },
            {
                "csv_location": "test_data/data/CIF_Parameters.csv",
                "reference_unit_cell": "test_data/ref/ref.res",
                "x_axis_header": "_diffrn_ambient_temperature",
            },
            {
                "atoms_for_analysis": ["Cu1"],
                "bond_data": "test_data/data/Bond_Lengths.csv",
                "angle_data": "test_data/data/Bond_Angles.csv",
                "torsion_data": "test_data/data/Bond_Torsions.csv",
            },
            {
                "cif_parameters": [
                    "_cell_length_a",
                    "_cell_length_b",
                    "_cell_length_c",
                    "_cell_angle_alpha",
                    "_cell_angle_beta",
                    "_cell_angle_gamma",
                    "_cell_volume",
                    "_diffrn_reflns_av_R_equivalents",
                    "_diffrn_measured_fraction_theta_full",
                    "_diffrn_ambient_temperature",
                    "_refine_ls_R_factor_gt",
                ],
                "atoms_for_analysis": ["Cu1"],
                "structural_analysis_angles": True,
                "structural_analysis_bonds": True,
                "structural_analysis_torsions": True,
                "ADP_analysis": True,
                "varying_cif_parameter": "_diffrn_ambient_temperature",
                "experiment_location": "test_data/data",
                "reference_unit_cell": "test_data/ref/ref.res",
            },
            {
                "experiment_location": "test_data/data",
                "reference_cif_location": "test_data/ref/ref.cif",
                "refinements_to_check": 4,
                "tolerance": 0.005,
                "maximum_cycles": 10,
                "cif_parameters": [
                    "_cell_length_a",
                    "_cell_length_b",
                    "_cell_length_c",
                    "_cell_angle_alpha",
                    "_cell_angle_beta",
                    "_cell_angle_gamma",
                    "_cell_volume",
                    "_diffrn_reflns_av_R_equivalents",
                    "_diffrn_measured_fraction_theta_full",
                    "_diffrn_ambient_temperature",
                    "_refine_ls_R_factor_gt",
                ],
                "structural_analysis_bonds": True,
                "structural_analysis_angles": True,
                "structural_analysis_torsions": True,
                "ADP_analysis": True,
                "atoms_for_analysis": ["Cu1"],
                "varying_cif_parameter": "_diffrn_ambient_temperature",
                "varying_parameter_values": [
                    "200(2)",
                    "210(2)",
                    "220(2)",
                    "230(2)",
                    "240(2)",
                ],
            },
            "General Kenobi",
        ]

    def test_config_true(self):
        """test correct message for self.cfg is returned when test_mode=True"""
        correct = "no conf.yaml file loaded"
        self.assertEqual(self.test.cfg, correct)

    def test_sys_true(self):
        """test contents of self.sys"""

        # Test that all the pre-filled fields that don't change are the same

        # First the intersection is checked - but this only checks top level and won't see if any of the parameters within each section have been removed or deleted

        required = set(self.correct_filled_params)
        present = set(self.test.sys).intersection(required)
        self.maxDiff = None
        self.assertEqual(required, present)

        # Makes sure that all the fields are present - note that the path changes from installation to usage

        # Checks that the new paths are correct (but only checks the new part added outside of the cx-asap package because depending on how the tests are run some of the files may not exist

        # Then changes the fields in the test to the old paths to make sure that it passes (assuming the new path does exist!)

        present_values = []
        for key in self.correct_filled_params:
            present_values.append(self.test.sys[key])

        for dic in present_values:
            for key in dic:
                if type(dic) == dict:
                    try:
                        if "test_data" in dic[key]:
                            original_path = re.search("test_data", dic[key])
                            new_path = dic[key][: original_path.start()]
                            if os.path.exists(new_path) == True:
                                dic[key] = dic[key][original_path.start() :]
                    except TypeError:
                        pass

        self.assertEqual(present_values, self.correct_fields)

        # Test that the fields that change are still present (but don't care what the value is)

        # Only system file, so we don't care what order the parameters appear in

        # I think the dumper used in the code vs the configuration does a different order

        correct_keys = sorted(list(self.correct_all_params.keys()))
        actual_keys = sorted(list(self.test.sys.keys()))
        self.assertEqual(correct_keys, actual_keys)


if __name__ == "__main__":
    unittest.main()
